apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: quay.io/hupiper/webinar:1.0
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/webinar.update-strategy: latest
  name: webinar-site
  namespace: openshift-gitops
spec:
  destination:
    namespace: webinar-site
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/webinar-site/overlays/webinar-site
    repoURL: https://github.com/hupiper/webinar-site-quay
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true